---
title: "Slow Regard"
author: "Adam"
date: "January, 2018"
output: 
html_document: 
self_contained: no
runtime: shiny
---


```{r echo=FALSE} 
library(knitr)
opts_chunk$set(echo=FALSE)
```

```{r,message=FALSE}

library(ggplot2)
library(dplyr)
library(keras)
library(readr)
library(stringr)
library(purrr)
library(tokenizers)

#library(knitr)
#library(tidyr)
#library(broom)
#library(grid)
# library(relaimpo)
# library(leaps)
#library(data.table)

```


```{R SHINYTRY, warning=FALSE}
model<- load_model_hdf5('C:/Users/setup/Dropbox/deeplearning/slowregard1/SlowRegard1.hd5')
text<- readRDS('C:/Users/setup/Dropbox/deeplearning/slowregard1/slowregard1text.RDS')
chars<- readRDS('C:/Users/setup/Dropbox/deeplearning/slowregard1/slowregard1chars.RDS')


```


```{r predict}
maxlen<-20
sample_mod <- function(preds, temperature = 1){
  preds <- log(preds)/temperature
  exp_preds <- exp(preds)
  preds <- exp_preds/sum(exp(preds))
  
  rmultinom(1, 1, preds) %>% 
    as.integer() %>%
    which.max()
}

diversity=1

# poem_length=as.integer(runif(n=1,min=200,max=2000))
poem_length=2000
# for(diversity in c(0.80)){  

cat(sprintf("diversity: %f ---------------\n\n", diversity))

start_index <- sample(1:(length(text) - maxlen), size = 1)
sentence <- text[start_index:(start_index + maxlen - 1)]
generated <- ""

#alternative way to seed with custom string:
sentence<-"just what was a wheel thinking"
# sentence<-"hey liz, what's up??" #must be 20 characters
# sentence<-"can't feel\nyour face"
cat(sentence)
sentence<-strsplit(sentence,split=NULL)[[1]]

# diversity=1

for(i in 1:poem_length){
  
  x <- sapply(chars, function(x){
    as.integer(x == sentence)
  })
  x <- array_reshape(x, c(1, dim(x)))
  
  preds <- predict(model, x)
  next_index <- sample_mod(preds, diversity)
  next_char <- chars[next_index]
  
  generated <- str_c(generated, next_char, collapse = "")
  sentence <- c(sentence[-1], next_char)
  
}

```

```{r}


inputPanel(
  
  sliderInput("TrialChoice", label = "Select a movement:",
              min=1,
              max=length(unique(hh$sacnum)),
              value=1,
              step=1)
  

)

renderPlot({
  
    chosentrial<-input$TrialChoice
    ggplot(filter(hh,sacnum==chosentrial))+
              geom_line(aes(counter,H),color='blue')+
             # geom_line(aes(counter,Ef),color='red')+
             geom_line(aes(counter,G),color='darkgreen')+
             geom_line(aes(counter,T),size=2,alpha=0.5)+
             geom_line(aes(counter,Hv/10),color='blue',linetype=2)+
             # geom_line(aes(counter,EV/10),color='red')+
             geom_line(aes(counter,Gv/10),color='darkgreen',linetype=2)+
             # geom_text(x=0,y=50,aes(label=round(sd(Gv),2)))+
             # geom_text(x=0,y=60,aes(label=firstshift[1]))+
             geom_line(aes(counter,sign(gazeshifts)*Gv/10),size=2,color='darkgreen',alpha=0.5)+
             geom_line(aes(counter,sign(headmovement)*Hv/10),color='blue',size=2,alpha=0.5)+
      theme_minimal()

})

```



